name: CI with Clang + Sanitizers

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          set -eux

          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y \
              clang meson ninja-build valgrind pkg-config cmake \
              zlib1g-dev libbz2-dev liblzma-dev
          elif command -v dnf >/dev/null 2>&1; then
            sudo dnf install -y \
              clang meson ninja-build valgrind pkg-config cmake \
              zlib-devel bzip2-devel xz-devel
          elif command -v yum >/dev/null 2>&1; then
            sudo yum install -y \
              clang meson ninja-build valgrind pkg-config cmake \
              zlib-devel bzip2-devel xz-devel
          else
            echo "error: unknown distro, please install zlib/bzip2/xz dev headers manually" >&2
            exit 1
          fi

      - name: Configure build with Meson (Clang + sanitizers)
        run: |
          CC=clang meson setup builddir \
            --buildtype=debug \
            -Db_sanitize=address,undefined \
            -Db_lundef=false

      - name: Build
        run: meson compile -C builddir

      - name: Test
        run: |
          meson test -C builddir || (cat builddir/meson-logs/testlog.txt && false)

      - name: Configure build for Valgrind run
        run: |
          meson setup build-valgrind \
            --buildtype=debug \
            -Db_sanitize=none

      - name: Build (Valgrind)
        run: meson compile -C build-valgrind

      - name: Test under Valgrind
        run: >
          meson test -C build-valgrind
          --wrap='valgrind --leak-check=full --show-leak-kinds=all
          --errors-for-leak-kinds=all --error-exitcode=1'
          || (cat build-valgrind/meson-logs/testlog.txt && false)

      - name: Run repository test script
        run: ./test.sh
